### ISSUE TITLE
Building on opensuse/ubuntu fail when building ide

### ISSUE THREAD

**Issue by eyecreate** [tiberiusbrown/abc#2]
When building the whole package/ide, compilation gets stuck on linking with it being unable to find a symbol. 

```
[ 13%] Linking CXX executable abc
/usr/bin/ld: CMakeFiles/abc.dir/src/ide_main.cpp.o: undefined reference to symbol 'XConvertSelection'
/usr/bin/ld: /lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
```
I noticed the github workflows show you building with emscripten, but is this also able to be compiled for desktops too?

**Comment by tiberiusbrown** [comment]
Thanks for the report. Should be [fixed ](https://github.com/tiberiusbrown/abc/commit/2e005e77fbcf04347bd8e69de17cd256ce3a7382) in master now.
