### ISSUE TITLE
Support arduboy mini 

### ISSUE THREAD

**Issue by eyecreate** [tiberiusbrown/abc#3]
I tried building my own version of the vm compiled for the arduboy mini, but I wasn't able to get it to run. It would be a great feature to be able to have the vm work on the mini and to select what kind of build device you want to output against dynamically.

**Comment by tiberiusbrown** [comment]
Good point. I'll add this soon.

**Comment by tiberiusbrown** [comment]
[Completed](https://github.com/tiberiusbrown/abc/commit/110fc56919de8357b9a2011e000af386adb60885). Thanks for the suggestion.
