### ISSUE TITLE
Allow selecting color of text when drawn

### ISSUE THREAD

**Issue by eyecreate** [tiberiusbrown/abc#4]
Right now, text can only be draw in white. It would be helpful to me if I could pick which color the text was drawn as.

**Comment by tiberiusbrown** [comment]
What do you think of making the font characters invert the pixels where they are drawn? Then text is white when drawn over a black background, and black when drawn over a white background.

**Comment by eyecreate** [comment]
What if they are drawn over non uniform background? (Like using dithering on the background) If that isn't a likely use case or is too difficult/expensive to implement your idea will still be an improvement over the current functions.

**Comment by tiberiusbrown** [comment]
In that case, you could $draw_filled_rect over the text area with your desired background color prior to text rendering. Even the current mode of text rendering doesn't overwrite the background -- in addition to performance reasons, doing it this way allows more freedom, particularly with a large font where you might not want the background of each glyph automatically cleared when rendering.

EDIT: Dazzle Dash does this (draw a black filled rectangle prior to drawing text) to render the timer and score overlays:
![recording_20240409144913](https://github.com/tiberiusbrown/abc/assets/16615838/d00ac45c-2f6c-4948-af42-8004d6b214fe)

**Comment by eyecreate** [comment]
That sounds good as a flexible solution without eating too much performance!

**Comment by tiberiusbrown** [comment]
[Pushed](https://github.com/tiberiusbrown/abc/commit/295bf409885aaf7ef1f4e9a0854c512d961af806) -- let me know if there's any issues. Thanks for the report!
