### ISSUE TITLE
Don't use MSVC specific debug feature with other compilers

### ISSUE THREAD

**Issue by eyecreate** [tiberiusbrown/abc#9]
I was updated my abc repo and ran into an issue when compiling with GCC. In this interp_generic code, it calls a MSVC specific debug function.
https://github.com/tiberiusbrown/abc/blob/99d3b46c8960f6fb6c67566a881faaad3621d166/interp_generic/abc_interpreter_sdl2.c#L191

Could this be ifdef-ed or something so that other compilers can not try to use this missing function?

**Comment by tiberiusbrown** [comment]
Thanks for letting me know. I've added an ifdef guard around that for MSVC. Sorry about that. That's in the generic interpreter which is still incomplete. It'll be completely removed eventually.
